language: python
python:
  - 3.5
install:
  - pip install coveralls
before_script:
  - git clone https://github.com/AaronKel/micropython.git
  - mv micropython micropython-dev
  - cd micropython-dev/unix
  - make axtls
  - make
  - ./micropython -m upip install micropython-unittest
  - cp ./micropython ../../
  - cd ../../
script:
  - ./micropython -m TestSuite
  - coverage run  TestSuite.py
after_success:
  - coveralls
